# User Roles
ADMIN = "ADMIN"
VENDOR = "VENDOR"
CUSTOMER = "CUSTOMER"

# Vendor Status
VENDOR_PENDING = "PENDING"
VENDOR_APPROVED = "APPROVED"
VENDOR_REJECTED = "REJECTED"

# Order Status
ORDER_PENDING = "PENDING"
ORDER_PROCESSING = "PROCESSING"
ORDER_SHIPPED = "SHIPPED"
ORDER_DELIVERED = "DELIVERED"
ORDER_CANCELLED = "CANCELLED"

# Payment Status
PAYMENT_PENDING = "PENDING"
PAYMENT_SUCCESS = "SUCCESS"
PAYMENT_FAILED = "FAILED"